name: Deploy dan-plugin-nsg

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  run:
    permissions:
      actions: read
      contents: read
    uses: data-altinn-no/deploy-actions/.github/workflows/dan-deploy-flow.yml@e9a1d62778d9d2f4e8c2245027fb2750fd230e0a
    with:
      artifact_name: 'dan-plugin-nsg' # Can be omitted, defaults to 'artifact'
      function_project_path: 'src/Altinn.Dan.Plugin.Nsg'
    secrets:
      function_app_name: ${{ secrets.FUNCTIONAPP_NAME }}
      publish_profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      resource_group_prod: ${{ secrets.RESOURCE_GROUP_PROD }}
      
